export const ROLE_KEYS = [
  "SUPER_ADMIN",
  "PLATFORM_ADMIN",
  "USER_ADMIN",
  "TOOL_ADMIN",
  "TOOL_EDITOR",
  "KNOWLEDGE_MANAGER",
  "SECURITY_REVIEWER",
  "ANALYTICS_VIEWER",
  "SUPPORT_AGENT",
  "AUDITOR",
  "USER",
] as const;

export type RoleKey = (typeof ROLE_KEYS)[number];

export const PERMISSION_KEYS = [
  "users.read",
  "users.create",
  "users.update",
  "users.suspend",
  "users.delete",
  "roles.read",
  "roles.manage",
  "groups.read",
  "groups.manage",
  "tools.read",
  "tools.create",
  "tools.update",
  "tools.review",
  "tools.approve",
  "tools.publish",
  "tools.pause",
  "tools.suspend",
  "tools.archive",
  "tools.assign",
  "knowledge.read",
  "knowledge.manage",
  "conversations.metadata.read",
  "conversations.content.read",
  "providers.read",
  "providers.manage",
  "analytics.read",
  "costs.read",
  "audit.read",
  "security.read",
  "settings.manage",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

const ALL_PERMISSIONS = [...PERMISSION_KEYS];

/** Declarative role → permission matrix. Seeded into roles/permissions/role_permissions at db:seed / db:migrate time. */
export const ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  PLATFORM_ADMIN: [
    "users.read",
    "users.update",
    "roles.read",
    "groups.read",
    "groups.manage",
    "tools.read",
    "tools.create",
    "tools.update",
    "tools.review",
    "tools.approve",
    "tools.publish",
    "tools.pause",
    "tools.suspend",
    "tools.archive",
    "tools.assign",
    "knowledge.read",
    "knowledge.manage",
    "conversations.metadata.read",
    "providers.read",
    "providers.manage",
    "analytics.read",
    "costs.read",
    "audit.read",
    "security.read",
    "settings.manage",
  ],
  USER_ADMIN: [
    "users.read",
    "users.create",
    "users.update",
    "users.suspend",
    "users.delete",
    "roles.read",
    "groups.read",
    "groups.manage",
  ],
  TOOL_ADMIN: [
    "tools.read",
    "tools.create",
    "tools.update",
    "tools.review",
    "tools.approve",
    "tools.publish",
    "tools.pause",
    "tools.suspend",
    "tools.archive",
    "tools.assign",
    "knowledge.read",
    "knowledge.manage",
    "analytics.read",
  ],
  TOOL_EDITOR: ["tools.read", "tools.create", "tools.update", "knowledge.read"],
  KNOWLEDGE_MANAGER: ["knowledge.read", "knowledge.manage", "tools.read"],
  SECURITY_REVIEWER: ["security.read", "audit.read", "tools.read", "tools.review"],
  ANALYTICS_VIEWER: ["analytics.read", "costs.read", "tools.read"],
  SUPPORT_AGENT: ["users.read", "conversations.metadata.read", "tools.read"],
  AUDITOR: ["audit.read", "security.read", "analytics.read", "tools.read", "users.read"],
  USER: [],
};
